import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "motion/react";

const ROWS = ["GET /users", "POST /payments", "GET /orders/{id}", "POST /auth/login", "GET /products", "PUT /cart"];
const COLS = [
  { k: "SLOW", c: "#4da3ff" },
  { k: "HANG", c: "#b14dff" },
  { k: "500", c: "#ff3d5a" },
  { k: "429", c: "#ff8a00" },
  { k: "{JSON", c: "#ffb020" },
  { k: "MISS", c: "#ffb020" },
  { k: "DRIFT", c: "#b14dff" },
  { k: "FLAKY", c: "#ff3d5a" },
];
// which cells are "in the matrix" (AI-selected)
const ACTIVE = new Set(["0-0", "0-2", "0-4", "0-5", "1-1", "1-2", "1-3", "1-7", "2-0", "2-5", "2-6", "3-1", "3-3", "3-7", "4-0", "4-4", "4-6", "5-2", "5-3", "5-7", "4-5", "0-6", "2-2"]);

const LOGS = [
  ["POST /payments", "429 · Retry-After: 3s", "client retried after 40ms", "bad"],
  ["GET /orders/ord_91", "200 · missing: total, items", "UI crashed: Cannot read 'map'", "bad"],
  ["POST /payments", "503 · flaky 1/3", "retry w/ same Idempotency-Key", "good"],
  ["GET /products", "200 · truncated JSON", "fell back to cached catalog", "good"],
  ["POST /auth/login", "hang 12s → 504", "no client timeout", "bad"],
  ["GET /users", "500 internal_error", "backoff 200ms → 400ms → ok", "good"],
  ["POST /payments", "timeout", "retried WITHOUT Idempotency-Key ⚠ double charge", "bad"],
  ["GET /products", "200 · schema drift v2", "validation caught unknown fields", "good"],
] as const;

export function HeroMatrix() {
  const [hot, setHot] = useState<string | null>(null);
  const [lines, setLines] = useState<{ id: number; l: (typeof LOGS)[number] }[]>([]);
  const n = useRef(0);
  useEffect(() => {
    const keys = [...ACTIVE];
    const t = setInterval(() => {
      setHot(keys[Math.floor(Math.random() * keys.length)]);
      const id = n.current++;
      setLines((prev) => [...prev.slice(-4), { id, l: LOGS[id % LOGS.length] }]);
    }, 900);
    return () => clearInterval(t);
  }, []);

  return (
    <div className="relative">
      <div className="absolute -inset-10 -z-10 rounded-[40px] bg-[radial-gradient(ellipse_at_center,rgba(255,61,90,0.18),transparent_60%)] blur-2xl" />
      <div className="chaos-border overflow-hidden rounded-2xl shadow-2xl">
        <div className="flex items-center gap-2 border-b border-line bg-raised/70 px-4 py-2.5">
          <span className="h-2.5 w-2.5 rounded-full bg-[#ff5f57]" />
          <span className="h-2.5 w-2.5 rounded-full bg-[#febc2e]" />
          <span className="h-2.5 w-2.5 rounded-full bg-[#28c840]" />
          <span className="ml-3 font-mono text-[11px] text-dim">chaos matrix · acme-store v2.4 · generated by Amazon Bedrock</span>
        </div>
        <div className="bg-panel p-4">
          <div className="grid gap-1.5" style={{ gridTemplateColumns: `128px repeat(${COLS.length}, minmax(0,1fr))` }}>
            <div />
            {COLS.map((c) => (
              <div key={c.k} className="text-center font-mono text-[9.5px] font-semibold tracking-wide text-dim">
                {c.k}
              </div>
            ))}
            {ROWS.map((r, ri) => (
              <Row key={r} r={r} ri={ri} hot={hot} />
            ))}
          </div>
          <div className="mt-4 h-[118px] overflow-hidden rounded-xl border border-line bg-[#09090f] p-3 font-mono text-[11px] leading-[1.55]">
            <AnimatePresence initial={false}>
              {lines.map(({ id, l }) => (
                <motion.div key={id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="flex gap-2 truncate">
                  <span className="text-dim">›</span>
                  <span className="text-[#d7d7e6]">{l[0]}</span>
                  <span className="text-chaos-orange">{l[1]}</span>
                  <span className={l[3] === "good" ? "text-mint" : "text-chaos-red"}>{l[3] === "good" ? "✓" : "✗"} {l[2]}</span>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </div>
      </div>
    </div>
  );

  function Row({ r, ri, hot }: { r: string; ri: number; hot: string | null }) {
    return (
      <>
        <div className="truncate pr-2 font-mono text-[11px] text-muted">
          <span style={{ color: r.startsWith("GET") ? "#22d3a5" : r.startsWith("POST") ? "#4da3ff" : "#ffb020" }}>{r.split(" ")[0]}</span> {r.split(" ")[1]}
        </div>
        {COLS.map((c, ci) => {
          const k = `${ri}-${ci}`;
          const active = ACTIVE.has(k);
          const isHot = hot === k;
          return (
            <motion.div
              key={k}
              animate={isHot ? { scale: [1, 1.18, 1], opacity: 1 } : { scale: 1 }}
              transition={{ duration: 0.45 }}
              className={`h-7 rounded-md border ${isHot ? "glitch" : ""}`}
              style={{
                background: active ? (isHot ? c.c : `${c.c}26`) : "#12121c",
                borderColor: active ? `${c.c}${isHot ? "ff" : "55"}` : "#1d1d2c",
                boxShadow: isHot ? `0 0 18px ${c.c}aa` : undefined,
              }}
            />
          );
        })}
      </>
    );
  }
}
